### ISSUE TITLE
Import Error with py_losc

### ISSUE THREAD

**Issue by luchini18** [Yang-Laboratory/losc#4]
I am trying to use the Python version of the code on a new environment using python=3.7, the docs said there was no need to compile anything so I was hoping this would be quick and easy but I think I'm having some trouble. 

To install the packages I did the following steps:

I installed psi4 python with the conda install on your docs page:
`conda install psi4=1.3.2 -c psi4`
and have numpy installed.

I downloaded this repository and added `{install-dir}/losc/src/py_losc` and `{install-dir}/losc/src/psi4_losc` to my PYTHONPATH variable. 

Then I tried to run the tests in /losc/tests/psi4_losc by running 
`python3 -m unittest test_scf_losc.py  --verbose` 
as suggested on the install docs, and receive the following error:

```
======================================================================
ERROR: test_scf_losc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_scf_losc
Traceback (most recent call last):
  File "{conda_install_dir}/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "{install_dir}/losc/tests/psi4_losc/test_scf_losc.py", line 6, in <module>
    import psi4_losc
  File "{install_dir}/losc/src/psi4_losc/psi4_losc.py", line 11, in <module>
    import py_losc
  File "{install_dir}/losc/src/py_losc/py_losc.py", line 2, in <module>
    from py_losc import py_losc_core as core
ImportError: cannot import name 'py_losc_core' from 'py_losc' ({install_dir}/losc/src/py_losc/py_losc.py)
```

Which I was confused about, I looked in the `py_losc.py` file and couldn't find any references to a `py_losc_core` other than that import. I get the same error whenever I try to import py_losc anywhere.

Am I missing a step in the installation? 
Thanks for any help.

**Comment by Miocbb** [comment]
`py_losc_core` is a library file, rather than a python file, and it is generated by compiling the C++ source code. It should locate as `{build_dir}/src/py_losc/py_losc_core.xxxx.so`, in which `{build_dir}` is your building directory. 

For the import failure, it looks like to me that you set up your `PYTHONPATH` variable incorrectly. I assume you did not run `make install` to install the library after your compilation. So all the python modules are located under `{build_dir}/src`. To make these python modules available, you should do `export PYTHONPATH=${PYTHONPATH}:{build_dir}/src`, rather than `{build_dir}/src/py_losc` or `{build_dir}/src/psi4_losc`. Also, please remember to replace `{build_dir}` with the full path of your building directory to make it work. For details, you can refer to step 4 as shown in the [manual](https://yang-laboratory.github.io/losc/installation.html#dependencies-and-tools).

**Comment by luchini18** [comment]
Hi
I've changed the PYTHONPATH to reference the src directory instead of the individual py_losc and psi4_losc directories. I made sure it contains the full path to the directory as well. It is now giving me a ModuleNotFound error 


```
test_scf_losc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_scf_losc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_scf_losc
Traceback (most recent call last):
  File "{conda_install_loc}/losc/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "{install_dir}/losc/tests/psi4_losc/test_scf_losc.py", line 6, in <module>
    import psi4_losc
  File "{install_dir}/losc/src/psi4_losc/__init__.py", line 11, in <module>
    import psi4_losc.scf
  File "{install_dir}/losc/src/psi4_losc/scf.py", line 7, in <module>
    import py_losc
  File "{install_dir}/losc/src/py_losc/__init__.py", line 22, in <module>
    from py_losc.py_losc_core import ao_hamiltonian_correction
ModuleNotFoundError: No module named 'py_losc.py_losc_core'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

Seems like a similar error just not finding the right files. 

So is the issue that I have not compiled the C++ source code? There are no .so files in my py_losc directory that I had downloaded so I think that's what's going on. I wasn't sure if it was completely necessary to compile to get the Python running - in the documentation [here](https://yang-laboratory.github.io/losc/installation.html) it says `For the Python parts of the LOSC library, namely the py_losc and psi4_losc modules, there is no need to compile.` but if I need to to get this `py_losc_core.so` file I can do that.

Thanks

**Comment by Miocbb** [comment]
Yes, the issue is because you did not compile the C++ source code to generate `py_losc_core`. The description in the manual is a bit misleading. Anyway, you still need to follow the 5 steps in the manual to make it work.

**Comment by luchini18** [comment]
Hello @Miocbb ,
Just getting back to this. I was able to successfully compile the C++ code and install the files but I think I am now having issues using the python library. I am following [these instructions](https://yang-laboratory.github.io/losc/installation.html) and in step 4 I set my PYTHONPATH to the first option given, referencing the install directory/liblosc folder. 

> export PYTHONPATH=${PYTHONPATH}:{DCMAKE_INSTALL_PREFIX}/liblosc

Where DCMAKE_INSTALL_PREFIX = /usr/local on my machine and the inside of the `liblosc/` folder contains the directories  `losc/  psi4_losc/  py_losc/  pyscf_losc/`

Do I need to individually add any of those folders to my PYTHONPATH as well or is having the liblosc in there good enough? 

Also are there any python version requirements for this package? I've been using python 3.7 but couldn't find if any older/newer versions were required from the documentation pages. 

When I get to step 5 and attempt to run tests I get errors importing the psi4_losc module which looks like it's coming in when trying to import the `py_losc` module.

>  import psi4_losc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/liblosc/psi4_losc/__init__.py", line 12, in <module>
    import psi4_losc.scf
  File "/usr/local/liblosc/psi4_losc/scf.py", line 7, in <module>
    import py_losc
  File "/usr/local/liblosc/py_losc/__init__.py", line 22, in <module>
    from py_losc.py_losc_core import ao_hamiltonian_correction
ModuleNotFoundError: No module named 'py_losc.py_losc_core'
>

It looks like it has a problem identifying the `py_losc_core` module from `py_losc`. When I look inside `/usr/local/liblosc/py_losc` the files present are `__init__.py`  `py_losc_core.cpython-38-x86_64-linux-gnu.so`  and `py_losc.py` 

Do I need to change the name of the `py_losc_core.cpython-38-x86_64-linux-gnu.so` file? Or make any edits to the python files? I checked and it's not a permissions issue. 

Thanks for any help!
